[tools]
actionlint = "1.7.12"
dprint = "0.57.0"
go = "1.27.1"
golangci-lint = "2.13.2"
goreleaser = "2.18.0"
node = "24.20.0"
"npm:renovate" = "43.288.0"
"pipx:commitizen" = "4.18.0"
prek = "0.5.2"
uv = "0.12.9"

[settings]
minimum_release_age = "3d"
lockfile = true

[hooks]
postinstall = { task = "postinstall" }
