[tools]
actionlint = "1.7.12"
dprint = "0.54.0"
go = "1.26.4"
golangci-lint = "2.12.2"
goreleaser = "2.16.0"
node = "24.16.0"
"npm:renovate" = "43.222.0"
"pipx:commitizen" = "4.16.3"
prek = "0.4.5"
uv = "0.11.21"

[settings]
minimum_release_age = "3d"
lockfile = true

[hooks]
postinstall = { task = "postinstall" }
