#!/usr/bin/env bash
#MISE description="Install prek git hooks after a local mise install (skipped on CI)"
#MISE dir="{{config_root}}"
#
# Wired into mise's postinstall hook (see mise.toml) so that `mise install`
# also wires up the prek-managed git hooks.
#
# Behavior:
#   - On CI: do nothing. Hooks are irrelevant there and we never want to mutate
#     .git/hooks during a CI run.
#   - When .git/hooks already holds prek-generated hooks: re-install quietly
#     (`prek install -q`) to keep an existing setup current without noise.
#   - Otherwise (first install): run `prek install` without -q so the developer
#     sees what got wired up.
#
# prek is part of the pinned toolchain, so by the time this postinstall hook
# runs it is guaranteed to be installed; no presence check is needed.
#
# `#MISE dir="{{config_root}}"` runs this from the repo root regardless of the
# caller's cwd, so the .git/hooks paths below resolve correctly.
set -euo pipefail

# Skip on CI. Most CI providers set $CI; treat any non-empty value as CI.
if [ -n "${CI:-}" ]; then
  exit 0
fi

# Only relevant inside a working tree with a .git/hooks directory.
if [ ! -d .git/hooks ]; then
  exit 0
fi

# Detect whether prek already manages the hooks by looking for its marker
# comment in the generated hook scripts.
if grep -ql "generated by prek" .git/hooks/* 2>/dev/null; then
  prek install -q
else
  prek install
fi
