name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/marketplace/actions/checkout
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Initialize tools
        uses: ./.github/actions/init-tools
        with:
          cache-key: ci

      - name: Download dependencies
        run: go mod download

      - name: Run tests
        run: go test -v -race ./...

      - name: Build
        run: go build -v ./...

  lint:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/marketplace/actions/checkout
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Initialize tools
        uses: ./.github/actions/init-tools
        with:
          cache-key: ci

      - name: golangci-lint
        run: golangci-lint run --timeout=5m
